apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tfalbr49n-dotnet-basic
  janus-idp.io/tekton: tfalbr49n-dotnet-basic
  backstage.io/kubernetes-id: tfalbr49n-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tfalbr49n-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
